historydb/account/urls.py
from django.urls import path
from django.urls import include

from . import views

app_name = "account"
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('reset-password/', views.reset_password, name='reset-password'),
    path('profile/', views.ProfileDashboard.as_view(), name='profile'),
    path('access-tokens/', views.AccessTokens.as_view(), name='access-tokens'),
    path('add-access-token/', views.AddAccessToken.as_view(), name='add-access-token'),
    path('user-groups/', views.UserGroups.as_view(), name='user-groups'),
    path('add-group/', views.AddGroup.as_view(), name='add-group'),
    path('update-roles/', views.UpdateRoles.as_view(), name='update-roles'),
    path('invite-member/', views.InviteMember.as_view(), name='invite-member'),
    path('data/', views.DataDashboard.as_view(), name='data'),
    path('<str:username>/activate/', views.activate, name='activate'),
]

historydb/documentation/urls.py
from django.urls import path
from django.urls import include

from . import views

app_name = "documentation"
urlpatterns = [
    path('documentation/<str:document_name>/', views.query, name='query'),
    path('gptune-user-guide/', views.gptune_user_guide, name='gptune-user-guide'),
    path('gptune-tutorial-slides-ecp2021/', views.gptune_tutorial_slides_ecp2021, name='gptune-tutorial-slides-ecp2021'),
    path('gptune-tutorial-slides-cass2026/', views.gptune_tutorial_slides_cass2026, name='gptune-tutorial-slides-cass2026'),
    path('gptune-hands-on/', views.gptune_hands_on, name='gptune-hands-on'),
    path('gptune-crowd-tuning/', views.gptune_crowd_tuning, name='gptune-crowd-tuning'),
    path('historydb-user-guide/', views.historydb_user_guide, name='historydb-user-guide'),
]

historydb/historydb/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('documentation/', include('documentation.urls')),
    path('repo/', include('repo.urls')),
    path('account/', include('account.urls')),
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

historydb/main/urls.py
from django.urls import path
from django.urls import include

from . import views

from django.conf.urls import url
from django.contrib import admin

app_name = "main"
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('about', views.about, name='about'),
    path('publications', views.publications, name='publications'),
    url(r'^docs/', include('docs.urls')),
    path('acknowledgement', views.acknowledgement, name='acknowledgement'),
    path('membership', views.membership, name='membership'),
    path('gptune-tutorial-ecp2021', views.gptune_tutorial_ecp2021, name='gptune-tutorial-ecp2021'),
    path('gptune-tutorial-ecp2022', views.gptune_tutorial_ecp2022, name='gptune-tutorial-ecp2022'),
    path('gptune-tutorial-ecp2023', views.gptune_tutorial_ecp2023, name='gptune-tutorial-ecp2023'),
    path('gptune-tutorial-cass2026', views.gptune_tutorial_cass2026, name='gptune-tutorial-cass2026'),
    path('release', views.release, name='release'),
    path('terms-of-use', views.terms_of_use, name='terms-of-use'),
    path('license', views.license, name='license'),
    path('examples', views.Examples.as_view(), name='examples'),
    path('base', views.base, name='base'),
]

historydb/repo/urls.py
from django.urls import path
from django.urls import include

from . import views

app_name = "repo"
urlpatterns = [
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('user-dashboard/', views.UserDashboard.as_view(), name='user-dashboard'),
    path('surrogate-model/', views.SurrogateModel.as_view(), name='surrogate-model'),
    path('model-prediction/', views.ModelPrediction.as_view(), name='model-prediction'),
    path('analysis-dashing-parameter/', views.AnalysisDashingParameter.as_view(), name='analysis-dashing-parameter'),
    path('analysis-dashing-counter/', views.AnalysisDashingCounter.as_view(), name='analysis-dashing-counter'),
    path('sadashboard/', views.SADashboard.as_view(), name='sadashboard'),
    path('sobol-analysis/', views.SobolAnalysis.as_view(), name='sobol-analysis'),
    path('entryaccess/', views.EntryAccess.as_view(), name='entryaccess'),
    path('entrydel/', views.EntryDel.as_view(), name='entrydel'),
    path('upload/', views.Upload.as_view(), name='upload'),
    path('tuning-problems/', views.TuningProblems.as_view(), name='tuning-problems'),
    path('add-tuning-problem-select/', views.AddTuningProblemSelect.as_view(), name='add-tuning-problem-select'),
    path('add-tuning-problem/', views.AddTuningProblem.as_view(), name='add-tuning-problem'),
    path('add-tuning-problem-flexible/', views.AddTuningProblemFlexible.as_view(), name='add-tuning-problem-flexible'),
    path('add-reproducible-workflow/', views.AddReproducibleWorkflow.as_view(), name='add-reproducible-workflow'),
    path('add-tuning-category/', views.AddTuningCategory.as_view(), name='add-tuning-category'),
    path('applications/', views.Applications.as_view(), name='applications'),
    path('add-applications/', views.AddApplications.as_view(), name='add-applications'),
    path('architectures/', views.Architectures.as_view(), name='architectures'),
    path('add-architectures/', views.Architectures.as_view(), name='add-architectures'),
    path('machines/', views.Machines.as_view(), name='machines'),
    path('add-machine/', views.AddMachine.as_view(), name='add-machine'),
    path('analytical-models/', views.AnalyticalModels.as_view(), name='analytical-models'),
    path('add-analytical-model/', views.AddAnalyticalModel.as_view(), name='add-analytical-model'),
    path('export/', views.Export.as_view(), name='export'),
    path('export-all/', views.ExportAll.as_view(), name='export-all'),
    path('direct-download/', views.direct_download, name='direct-download'),
    path('direct-upload/', views.direct_upload, name='direct-upload'),
    path('api-test/', views.api_test, name='api-test'),
    path('archive/<str:perf_data_uid>/', views.query, name='query'),
]

historydb/main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from dbmanager import HistoryDB_MongoDB
from django.contrib.auth import get_user_model
import json

class Index(TemplateView):

    def get(self, request, **kwargs):
        print ("======== Examples GET ========")

        historydb = HistoryDB_MongoDB()

        user_email = ""
        if request.user.is_authenticated:
            user_email = request.user.email

        User = get_user_model()
        user_count = len(User.objects.all())

        context = {
                "stats": {
                        "num_tuning_problems": historydb.get_num_tuning_problems(),
                        "num_function_evaluations": historydb.get_num_function_evaulations(),
                        "num_users": user_count
                    }
                }

        return render(request, 'main/index.html', context)

def about(request):
    return render(request, 'main/about.html')

def publications(request):
    return render(request, 'main/publications.html')

def acknowledgement(request):
    return render(request, 'main/acknowledgement.html')

def membership(request):
    return render(request, 'main/membership.html')

class Examples(TemplateView):

    def get(self, request, **kwargs):
        historydb = HistoryDB_MongoDB()

        tuning_problems_avail_per_category = historydb.load_tuning_problems_per_category()
        context = { "tuning_problems_avail_per_category": tuning_problems_avail_per_category }

        return render(request, 'main/examples.html', context)

    def post(self, request, **kwargs):

        historydb = HistoryDB_MongoDB()

        tuning_problems_avail = historydb.load_all_tuning_problems()

        tuning_problem_unique_name = request.POST["tuning_problem_unique_name"]
        if tuning_problem_unique_name == "":
            context = {
                "header": "Something went wrong",
                "message": "Please choose a tuning problem to search"
            }
            return render(request, 'main/error.html', context)

        machine_configurations_avail = historydb.get_machine_configurations_avail()
        software_configurations_avail = historydb.get_software_configurations_avail()
        outputs_avail = historydb.get_outputs_avail()
        user_configurations_avail = historydb.get_user_configurations_avail()
        tuning_problem_info = historydb.get_tuning_problem_info(tuning_problem_unique_name)

        machine_configurations_list = machine_configurations_avail[tuning_problem_unique_name]
        software_configurations_list = software_configurations_avail[tuning_problem_unique_name]
        output_options = outputs_avail[tuning_problem_unique_name]
        user_configurations_list = user_configurations_avail[tuning_problem_unique_name]

        user_email = request.user.email if request.user.is_authenticated else ""

        search_options = ['func_eval']

        if "func_eval" in search_options:
            func_eval_list = historydb.load_func_eval_filtered(tuning_problem_unique_name = tuning_problem_unique_name,
                    machine_configurations_list = machine_configurations_list,
                    software_configurations_list = software_configurations_list,
                    output_options = output_options,
                    user_configurations_list = user_configurations_list,
                    user_email = user_email)
            num_func_eval = len(func_eval_list)
            for i in range(num_func_eval):
                func_eval_list[i]["id"] = i
        else:
            func_eval_list = []
            num_func_eval = 0

        if "surrogate_model" in search_options:
            surrogate_model_list = historydb.load_surrogate_models_filtered(tuning_problem_unique_name = tuning_problem_unique_name,
                    machine_configurations_list = machine_configurations_list,
                    software_configurations_list = software_configurations_list,
                    output_options = output_options,
                    user_configurations_list = user_configurations_list,
                    user_email = user_email)
            num_surrogate_models = {}
            for output_option in output_options:
                num_surrogate_models[output_option] = len(surrogate_model_list[output_option])

            for output_option in output_options:
                i = 0
                for surrogate_model in surrogate_model_list[output_option]:
                    surrogate_model["id"] = i
                    i += 1
                    surrogate_model["num_func_eval"] = len(surrogate_model["function_evaluations"])
                    surrogate_model["num_task_parameters"] = len(surrogate_model["task_parameters"])
                    surrogate_model["num_func_eval_per_task"] = \
                            int(len(surrogate_model["function_evaluations"])/len(surrogate_model["task_parameters"]))
        else:
            surrogate_model_list = {}
            for output_option in output_options:
                surrogate_model_list[output_option] = []

            num_surrogate_models = {}
            for output_option in output_options:
                num_surrogate_models[output_option] = 0

        print ("machine_configurations_avail: ", machine_configurations_avail)
        print ("software_configurations_avail: ", software_configurations_avail)
        print ("outputs_avail: ", outputs_avail)
        print ("user_configurations_avail: ", user_configurations_avail)

        print ("tuning_problem_unique_name: ", tuning_problem_unique_name)
        print ("tuning_problem_info: ", tuning_problem_info)
        print ("machine_configurations_list: ", machine_configurations_list)
        print ("software_configurations_list: ", software_configurations_list)
        print ("user_configurations_list: ", user_configurations_list)
        print ("output_options: ", output_options)
        print ("search_options: ", search_options)

        print ("num_surrogate_models: ", num_surrogate_models)

        context = {
                "tuning_problem_unique_name" : tuning_problem_unique_name,
                "tuning_problem_info" : tuning_problem_info,
                "tuning_problems_avail" : tuning_problems_avail,
                "machine_configurations_avail" : machine_configurations_avail,
                "software_configurations_avail" : software_configurations_avail,
                "outputs_avail" : outputs_avail,
                "user_configurations_avail" : user_configurations_avail,
                "func_eval_list" : func_eval_list,
                "num_func_eval" : num_func_eval,
                "surrogate_model_list" : surrogate_model_list,
                "num_surrogate_models" : num_surrogate_models,
                "machine_configurations_list" : json.dumps(machine_configurations_list),
                "software_configurations_list" : json.dumps(software_configurations_list),
                "output_options" : json.dumps(output_options),
                "user_configurations_list" : json.dumps(user_configurations_list),
                "search_options" : json.dumps(search_options)
                }

        return render(request, 'repo/dashboard.html', context)

def gptune_tutorial_ecp2021(request):
    return render(request, 'main/ecp2021.html')

def gptune_tutorial_ecp2022(request):
    return render(request, 'main/ecp2022.html')

def gptune_tutorial_ecp2023(request):
    return render(request, 'main/ecp2023.html')

def gptune_tutorial_cass2026(request):
    return render(request, 'main/cass2026.html')

def release(request):
    return render(request, 'main/release.html')

def terms_of_use(request):
    return render(request, 'main/terms-of-use.html')

def license(request):
    return render(request, 'main/license.html')

def base(request):
    return render(request, 'main/base.html')

historydb/main/templates/main/base.html
<!-- Author: Younghyun Cho <younghyun@berkeley.edu> -->

<!doctype html>

{% load static %}
<html lang="en" style="background-color:#00313C">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <!-- <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors"> -->
  <meta name="author" content="Younghyun Cho">
  <!-- <meta name="generator" content="Jekyll v4.1.1"> -->

  <title>GPTune History Database</title>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

  <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
  <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>
  <script src="https://cdn.datatables.net/select/1.3.3/js/dataTables.select.min.js"></script>

  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/select/1.3.3/css/select.dataTables.min.css">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
</head>

<body style="padding-top: 50px">

  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top" style="background-color: white;">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item" id="nav-item-home">
          <a class="nav-link" href="{% url 'main:index' %}">Home<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown" id="nav-item-about">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">About</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="{% url 'main:about' %}">About</a>
            <a class="dropdown-item" href="{% url 'main:publications' %}">Publications</a>
          </div>
        </li>
        <li class="nav-item dropdown" id="nav-item-gptune">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">GPTune</a>
          <div class="dropdown-menu" aria-labelledby="dropdown02">
            <a class="dropdown-item" href="https://github.com/gptune/GPTune">GPTune GitHub</a>
            <a class="dropdown-item" href="{% url 'documentation:gptune-user-guide' %}">GPTune User Guide</a>
            <a class="dropdown-item" href="https://github.com/gptune/GPTune/tree/master/FAQ">Frequently Asked Questions</a>
            <a class="dropdown-item" href="https://github.com/gptune/GPTune/issues">Issue Report (Get Help from Developers)</a>
            <a class="dropdown-item" href="https://forms.gle/WdjQbcJk3iwC9mzv5">User Survey (User Feedback)</a>
            <a class="dropdown-item" href="{% url 'main:release' %}">Release</a>
          </div>
        </li>
        <li class="nav-item dropdown" id="nav-item-repo">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">History Database</a>
          <div class="dropdown-menu" aria-labelledby="dropdown03">
            <a class="dropdown-item" href="{% url 'repo:dashboard' %}">Dashboard (Performance Data Browser)</a>
            <a class="dropdown-item" href="{% url 'repo:upload' %}">Upload Performance Data</a>
            <a class="dropdown-item" href="{% url 'repo:tuning-problems' %}">Tuning Problems</a>
            <a class="dropdown-item" href="{% url 'repo:machines' %}">Machine List</a>
            <a class="dropdown-item" href="{% url 'repo:analytical-models' %}">Analytical Models (under construction)</a>
            <a class="dropdown-item" href="{% url 'main:examples' %}">Popular Tuning Examples</a>
            <a class="dropdown-item" href="{% url 'main:membership' %}">About User Privileges</a>
          </div>
        </li>
        <li class="nav-item dropdown" id="nav-item-tutorial">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Tutorial</a>
          <div class="dropdown-menu" aria-labelledby="dropdown04">
            <a class="dropdown-item" href="{% url 'main:gptune-tutorial-cass2026' %}">GPTune Tutorial (CASS BoF 2026)</a>
            <a class="dropdown-item" href="{% url 'main:gptune-tutorial-ecp2023' %}">GPTune Tutorial (ECP Annual Meeting 2023)</a>
            <a class="dropdown-item" href="{% url 'main:gptune-tutorial-ecp2022' %}">GPTune Tutorial (ECP Annual Meeting 2022)</a>
            <a class="dropdown-item" href="{% url 'main:gptune-tutorial-ecp2021' %}">GPTune Tutorial (ECP Annual Meeting 2021)</a>
          </div>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item dropdown" id="nav-item-account">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Signed In As {{ user.username }}</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="{% url 'account:profile' %}">My Profile</a>
            <a class="dropdown-item" href="{% url 'account:reset-password' %}">Reset password</a>
            <a class="dropdown-item" href="{% url 'account:access-tokens' %}">Access Tokens</a>
            <a class="dropdown-item" href="{% url 'account:user-groups' %}">Collaboration Groups</a>
            <a class="dropdown-item" href="{% url 'repo:user-dashboard' %}">My Data</a>
            <a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item" id="nav-item-login">
          <a class="nav-link" href="{% url 'account:login' %}">Log In To History Databae</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <main role="main">
    {% block content %}
    {% endblock %}
    <br><br><br><br>
    <footer style="text-align:left; background-color:#00313C; color:white">
      <div class="container px-4 py-4">
        <p>&copy; 2021 GPTune-Dev. <a href="mailto: gptune-dev@lbl.gov">gptune-dev@lbl.gov</a>. All rights reserved.</p>
        <p>
        GPTune is a joint research project between <a href="https://lbl.gov">Lawrence Berkeley National Laboratory</a> and <a href="https://berkeley.edu">University of California at Berkeley</a>, and is part of the <a href="https://xsdk.info/ecp/">xSDK4ECP</a> effort supported by the <a href="https://www.exascaleproject.org/">Exascale Computing Project (ECP)</a>.
        </p>
        <a href="{% url 'main:terms-of-use'%}">Terms of Use</a>
        <br>
        <a href="{% url 'main:license'%}">License</a>
      </div>
    </footer>
  </main>
</body>
</html>

historydb/main/templates/main/gptune-tutorial-ecp2021.html
<!-- Author: Younghyun Cho <younghyun@berkeley.edu> -->

<!doctype html>

{% extends 'main/base.html' %}
{% load static %}

{% block content %}

<script>
  $(document).ready(function () {
    $('#nav-item-about').addClass('active');
  });
</script>

<div class="container">
  <br><br>

  <h1>GPTune Tutorial Materials - ECP Annual Meeting 2021</h1>
  <p class="lead">
    <ul>
      <h3>
        <li>
          <a href="{% url 'documentation:gptune-tutorial-slides-ecp2021' %}">Presentation Slides</a>
        </li>
        <li>
          <a href="{% url 'documentation:gptune-hands-on' %}">Instruction for Hands-on Exercises</a>
        </li>
        <li>
          <a href="https://forms.gle/BGwpWr76Z9pa6oMr7">Link to Survey</a>
        </li>
        <li>
          <a href="{% url 'documentation:gptune-user-guide' %}">Users Guide</a>
        </li>
        <li>
          <a href="https://github.com/gptune/GPTune">Github</a>
        </li>
      </h3>
    </ul>
  </p>

</div>

{% endblock %}

historydb/main/templates/main/publications.html
<!-- Author: Younghyun Cho <younghyun@berkeley.edu> -->

<!doctype html>

{% extends 'main/base.html' %}
{% load static %}

{% block content %}

<script>
  $(document).ready(function () {
    $('#nav-item-about').addClass('active');
  });
</script>

<div>
  <hr>
  <div class="container px-4 py-5" style="background-color:#EAEDED">
    <h1>Publications</h1>
    <p class="lead">
    <ul class="lead">
      <li>Enhancing Beam Intensity in RHIC EBIS Beamline via GPTune Machine Learning-driven Optimization, 15th IPAC, 2024 <a href="https://inspirehep.net/files/bf6f4573844ee68623a5b185cf3bc8f7">(Link)</a></li>
      <li>Efficient and Robust Bayesian Selection of Hyperparameters in Dimension Reduction for Visualization, arxiv preprint arXiv:2306.00357 <a href="https://arxiv.org/abs/2306.00357">(Link)</a></li>
      <li>Detecting resonance of radio-frequency cavities using fast direct integral equation solvers and augmented Bayesian optimization, arxiv preprint arXiv:2305.05918 <a href="https://arxiv.org/abs/2305.05918">(Link)</a></li>
      <li>Non-smooth Bayesian optimization in tuning scientific applications, in the International Journal of High Performance Computing Applications <a href="https://journals.sagepub.com/doi/abs/10.1177/10943420241278981">(Link)</a> <a href="https://arxiv.org/abs/2109.07563">(arXiv version)</a></li>
      <li>Hybrid parameter search and dynamic model selection for mixed-variable Bayesian optimization, in Journal of Computational and Graphical Statistics <a href="https://www.tandfonline.com/doi/abs/10.1080/10618600.2024.2308216">(Link)</a> <a href="https://arxiv.org/abs/2206.01409">(arXiv version)</a></li>
      <li>Harnessing the Crowd for Autotuning HPC Applications, IEEE IPDPS 2023 <a href="https://ieeexplore.ieee.org/document/10177466">(Link)</a></li>
      <li>GPTuneBand: Multi-task and Multi-fidelity Autotuning for Large-scale High Performance Computing Applications, 2022 SIAM Conference on Parallel Processing for Scientific Computing <a href="https://epubs.siam.org/doi/abs/10.1137/1.9781611977141.1">(Link)</a></li>
      <li>Enhancing Autotuning Capability with a History Database, MCSoC-2021, Special Session: Autotuning for Multicore & GPU <a href="https://ieeexplore.ieee.org/document/9691973">(Link)</a></li>
      <li>GPTune: multitask learning for autotuning exascale applications, PPoPP 2021 <a href="https://dl.acm.org/doi/abs/10.1145/3437801.3441621">(Link)</a></li>
      <li>Multitask and transfer learning for autotuning exascale applications, arXiv preprint arXiv:1908.05792 <a href="https://arxiv.org/abs/1908.05792">(Link)</a></li>
    </ul>
    </p>
  </div>

  <hr>
  <div class="container px-4 py-5" style="background-color:#EAEDED">
    <h1>Talks/Media</h1>
    <p class="lead">
    <ul class="lead">
      <li>Performance Autotuning of ECP Applications with Gaussian Process Based and Cloud Database Enhanced, Tutorial at ECP Annual Meeting 2022 <a href="https://www.youtube.com/watch?v=NBoDoFAm5wE">(Link)</a></li>
      <li>Enhancing Autotuning Capability with a History Database, MCSoC-2021, Special Session: Autotuning for Multicore & GPU, December 22, 2021 <a href="https://drive.google.com/file/d/1t-cMJ_jvdhJD3A4bRUAn8pmtM0MGvXpv/view?usp=sharing">(Link)</a></li>
      <li>GPTune: Multitask Learning for Autotuning Exascale Applications, PPoPP 2021, February 27, 2021 <a href="https://www.youtube.com/watch?v=QDcZTEKh_b0">(Link)</a></li>
      <li>Autotuning exascale applications with Gaussian Process Regression, E-NLA Seminar, October 14, 2020 <a href="https://www.youtube.com/watch?v=Xnj8FDquMgI&t=287s">(Link)</a></li>
    </ul>
    </p>
  </div>

  <hr>
  <div class="container px-4 py-5" style="background-color:#EAEDED">
    <h1>Tutorials</h1>
    <p class="lead">
    <ul class="lead">
      <li>GPTune: Performance Autotuner for ECP Applications, Tutorial at ECP Annual Meeting 2023 <a href="{% url 'main:gptune-tutorial-ecp2023' %}">(Link)</a></li>
      <li>GPTune: Performance Autotuner for ECP Applications, Tutorial at ECP Annual Meeting 2022 <a href="{% url 'main:gptune-tutorial-ecp2022' %}">(Link)</a></li>
      <li>GPTune: Performance Autotuner for ECP Applications, Tutorial at ECP Annual Meeting 2021 <a href="{% url 'main:gptune-tutorial-ecp2021' %}">(Link)</a></li>
    </ul>
    </p>
  </div>

  <hr>
  <div class="container px-4 py-5" style="background-color:#EAEDED">
    <h1>White papers</h1>
    <p class="lead">
    <ul class="lead">
      <li>Crowd-tuning with GPTune History Database: Design Overview, Data-sharing Policy, and Plan to Maintain Security <a href="{% url 'documentation:gptune-crowd-tuning' %}">(Link)</a></li>
    </ul>
    </p>

  </div>
</div>

{% endblock %}