historydb/account/urls.py
from django.urls import path
from django.urls import include

from . import views

app_name = "account"
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('reset-password/', views.reset_password, name='reset-password'),
    path('profile/', views.ProfileDashboard.as_view(), name='profile'),
    path('access-tokens/', views.AccessTokens.as_view(), name='access-tokens'),
    path('add-access-token/', views.AddAccessToken.as_view(), name='add-access-token'),
    path('user-groups/', views.UserGroups.as_view(), name='user-groups'),
    path('add-group/', views.AddGroup.as_view(), name='add-group'),
    path('update-roles/', views.UpdateRoles.as_view(), name='update-roles'),
    path('invite-member/', views.InviteMember.as_view(), name='invite-member'),
    path('data/', views.DataDashboard.as_view(), name='data'),
    path('<str:username>/activate/', views.activate, name='activate'),
]

historydb/documentation/urls.py
from django.urls import path
from django.urls import include

from . import views

app_name = "documentation"
urlpatterns = [
    path('documentation/<str:document_name>/', views.query, name='query'),
    path('gptune-user-guide/', views.gptune_user_guide, name='gptune-user-guide'),
    path('gptune-tutorial-slides-ecp2021/', views.gptune_tutorial_slides_ecp2021, name='gptune-tutorial-slides-ecp2021'),
    path('gptune-tutorial-slides-cass2026/', views.gptune_tutorial_slides_cass2026, name='gptune-tutorial-slides-cass2026'),
    path('gptune-hands-on/', views.gptune_hands_on, name='gptune-hands-on'),
    path('gptune-crowd-tuning/', views.gptune_crowd_tuning, name='gptune-crowd-tuning'),
    path('historydb-user-guide/', views.historydb_user_guide, name='historydb-user-guide'),
]

historydb/historydb/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('documentation/', include('documentation.urls')),
    path('repo/', include('repo.urls')),
    path('account/', include('account.urls')),
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

historydb/main/urls.py
from django.urls import path
from django.urls import include

from . import views

from django.conf.urls import url
from django.contrib import admin

app_name = "main"
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('about', views.about, name='about'),
    path('publications', views.publications, name='publications'),
    url(r'^docs/', include('docs.urls')),
    path('acknowledgement', views.acknowledgement, name='acknowledgement'),
    path('membership', views.membership, name='membership'),
    path('gptune-tutorial-ecp2021', views.gptune_tutorial_ecp2021, name='gptune-tutorial-ecp2021'),
    path('gptune-tutorial-ecp2022', views.gptune_tutorial_ecp2022, name='gptune-tutorial-ecp2022'),
    path('gptune-tutorial-ecp2023', views.gptune_tutorial_ecp2023, name='gptune-tutorial-ecp2023'),
    path('gptune-tutorial-cass2026', views.gptune_tutorial_cass2026, name='gptune-tutorial-cass2026'),
    path('release', views.release, name='release'),
    path('terms-of-use', views.terms_of_use, name='terms-of-use'),
    path('license', views.license, name='license'),
    path('examples', views.Examples.as_view(), name='examples'),
    path('base', views.base, name='base'),
]

historydb/repo/urls.py
from django.urls import path
from django.urls import include

from . import views

app_name = "repo"
urlpatterns = [
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('user-dashboard/', views.UserDashboard.as_view(), name='user-dashboard'),
    path('surrogate-model/', views.SurrogateModel.as_view(), name='surrogate-model'),
    path('model-prediction/', views.ModelPrediction.as_view(), name='model-prediction'),
    path('analysis-dashing-parameter/', views.AnalysisDashingParameter.as_view(), name='analysis-dashing-parameter'),
    path('analysis-dashing-counter/', views.AnalysisDashingCounter.as_view(), name='analysis-dashing-counter'),
    path('sadashboard/', views.SADashboard.as_view(), name='sadashboard'),
    path('sobol-analysis/', views.SobolAnalysis.as_view(), name='sobol-analysis'),
    path('entryaccess/', views.EntryAccess.as_view(), name='entryaccess'),
    path('entrydel/', views.EntryDel.as_view(), name='entrydel'),
    path('upload/', views.Upload.as_view(), name='upload'),
    path('tuning-problems/', views.TuningProblems.as_view(), name='tuning-problems'),
    path('add-tuning-problem-select/', views.AddTuningProblemSelect.as_view(), name='add-tuning-problem-select'),
    path('add-tuning-problem/', views.AddTuningProblem.as_view(), name='add-tuning-problem'),
    path('add-tuning-problem-flexible/', views.AddTuningProblemFlexible.as_view(), name='add-tuning-problem-flexible'),
    path('add-reproducible-workflow/', views.AddReproducibleWorkflow.as_view(), name='add-reproducible-workflow'),
    path('add-tuning-category/', views.AddTuningCategory.as_view(), name='add-tuning-category'),
    path('applications/', views.Applications.as_view(), name='applications'),
    path('add-applications/', views.AddApplications.as_view(), name='add-applications'),
    path('architectures/', views.Architectures.as_view(), name='architectures'),
    path('add-architectures/', views.Architectures.as_view(), name='add-architectures'),
    path('machines/', views.Machines.as_view(), name='machines'),
    path('add-machine/', views.AddMachine.as_view(), name='add-machine'),
    path('analytical-models/', views.AnalyticalModels.as_view(), name='analytical-models'),
    path('add-analytical-model/', views.AddAnalyticalModel.as_view(), name='add-analytical-model'),
    path('export/', views.Export.as_view(), name='export'),
    path('export-all/', views.ExportAll.as_view(), name='export-all'),
    path('direct-download/', views.direct_download, name='direct-download'),
    path('direct-upload/', views.direct_upload, name='direct-upload'),
    path('api-test/', views.api_test, name='api-test'),
    path('archive/<str:perf_data_uid>/', views.query, name='query'),
]

historydb/documentation/models.py
from django.db import models

# Create your models here.

historydb/documentation/views.py
from django.shortcuts import render

import markdown
from django.utils.safestring import mark_safe

from pathlib import Path
import os

def markdown_to_html(value):
    #extensions = ["nl2br", "fenced_code"]
    extensions = ["fenced_code"]
    return mark_safe(markdown.markdown(value, extensions=extensions))

# Create your views here.
def query(request, document_name):
    documentation_dir = Path(__file__).resolve().parent.parent.parent
    documentation_file = os.path.join(documentation_dir, 'documentation/'+document_name+'.md')
    with open(documentation_file) as f_in:
        markdown_string = f_in.read()
        markdown_html = markdown_to_html(markdown_string)

    context = {
            "document_name" : document_name,
            "markdown_html" : markdown_html
            }

    print (context)

    return render(request, 'documentation/query.html', context)

from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse

def gptune_user_guide(request):
    fs = FileSystemStorage()

    with fs.open('GPTune_UsersGuide.pdf') as pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = 'inline;filename=some_file.pdf'
        return response

def gptune_tutorial_slides_ecp2021(request):
    fs = FileSystemStorage()

    with fs.open('GPTune_Tutorial.pdf') as pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = 'inline;filename=some_file.pdf'
        return response

def gptune_tutorial_slides_cass2026(request):
    fs = FileSystemStorage()

    with fs.open('GPTune_Tutorial-CASS_BoF_2026_compact.pdf') as pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = 'inline;filename=some_file.pdf'
        return response

def gptune_hands_on(request):
    fs = FileSystemStorage()

    with fs.open('GPTune_HandsOnInstructions.pdf') as pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = 'inline;filename=some_file.pdf'
        return response

def gptune_crowd_tuning(request):
    fs = FileSystemStorage()

    with fs.open('Crowd_tuning_with_GPTune.pdf') as pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = 'inline;filename=some_file.pdf'
        return response

from django.shortcuts import redirect
def historydb_user_guide(request):
    return redirect('https://gptune-history-database.readthedocs.io/en/latest/')

historydb/documentation/templates/documentation/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Jekyll v4.1.1">

  <title>GPTune History Database</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'css/carousel.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script>window.jQuery || document.write('')</script>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

  <script type="text/javascript" src="{% static 'js/dashboard.js' %}"></script>
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#">GPTune History DB</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item" id="nav-item-home">
          <a class="nav-link" href="{% url 'main:index' %}">Home<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown" id="nav-item-about">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">About</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="{% url 'main:about' %}">About</a>
            <a class="dropdown-item" href="https://github.com/gptune/GPTune">Github</a>
          </div>
        </li>
        <li class="nav-item dropdown" id="nav-item-repo">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Repository</a>
          <div class="dropdown-menu" aria-labelledby="dropdown02">
            <a class="dropdown-item" href="{% url 'repo:dashboard' %}">Dashboard (Performance Data Browser)</a>
            <a class="dropdown-item" href="{% url 'repo:upload' %}">Upload Performance Data</a>
            <a class="dropdown-item" href="{% url 'repo:tuning-problems' %}">Open Tuning Problems</a>
            <a class="dropdown-item" href="{% url 'repo:machines' %}">Machine List</a>
          </div>
        </li>
        <li class="nav-item dropdown" id="nav-item-documentation">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Documentation</a>
          <div class="dropdown-menu" aria-labelledby="dropdown03">
            <a class="dropdown-item" href="{% url 'documentation:query' document_name='historydb_motivation' %}">Manual</a>
          </div>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item dropdown" id="nav-item-account">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Signed In As {{ user.username }}</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="{% url 'account:profile' %}">My Profile</a>
            <a class="dropdown-item" href="{% url 'repo:user-groups' %}">My Groups</a>
            <a class="dropdown-item" href="{% url 'repo:user-dashboard' %}">My Data</a>
            <a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item" id="nav-item-login">
          <a class="nav-link" href="{% url 'account:login' %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <main role="main">
    {% block content %}
    {% endblock %}
    <footer class="container" style="margin-left:25%; margin-right:10%;">
      <hr>
      <p>&copy; 2021 GPTune-Dev. All rights reserved.</p>
    </footer>
  </main>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
</body>

</html>

historydb/documentation/templates/documentation/query.html
{% extends 'documentation/base.html' %}
{% load static %}
{% block content %}

<style>

li a {
  display: block;
  color: #000;
  padding: 0px 16px;
  text-decoration: none;
}

li a.active {
  background-color: #4CAF50;
  color: white;
}

li a:hover:not(.active) {
  background-color: #555;
  color: white;
}

</style>

<link rel="stylesheet" href="{% static 'css/github.css' %}">

<div>
  <ul style="list-style-type: none; margin: 0; padding: 0; width: 20%; background-color: #f1f1f1; position: fixed; height: 100%; overflow: auto;">
    <font size=3px>

    <li><a href="{% url 'documentation:query' document_name='historydb_motivation' %}"><b>History DB</b></a></li>

    {% ifequal document_name 'historydb_motivation' %}
    <li><a class="active" href="{% url 'documentation:query' document_name='historydb_motivation' %}">Motivation</a></li>
    {% else %}
    <li><a href="{% url 'documentation:query' document_name='historydb_motivation' %}">Motivation</a></li>
    {% endifequal %}

    {% ifequal document_name 'historydb_features' %}
    <li><a class="active" href="{% url 'documentation:query' document_name='historydb_features' %}">Features</a></li>
    {% else %}
    <li><a href="{% url 'documentation:query' document_name='historydb_features' %}">Features</a></li>
    {% endifequal %}

    <br>

    <li><a href="{% url 'documentation:query' document_name='userguide_funceval' %}"><b>User Guide</b></a></li>

    {% ifequal document_name 'userguide_funceval' %}
    <li><a class="active" href="{% url 'documentation:query' document_name='userguide_funceval' %}">Function Evaluation Data</a></li>
    {% else %}
    <li><a href="{% url 'documentation:query' document_name='userguide_funceval' %}">Function Evaluation Data</a></li>
    {% endifequal %}

    {% ifequal document_name 'userguide_surrogatemodel' %}
    <li><a class="active" href="{% url 'documentation:query' document_name='userguide_surrogatemodel' %}">Surrogate Models</a></li>
    {% else %}
    <li><a href="{% url 'documentation:query' document_name='userguide_surrogatemodel' %}">Surrogate Models</a></li>
    {% endifequal %}

    <br>

    <li><a class="disabled" href="#"><b>CK-GPTune</b></a></li>

    {% ifequal document_name 'ckgptune_background' %}
    <li><a class="active" href="{% url 'documentation:query' document_name='ckgptune_background' %}">Background</a></li>
    {% else %}
    <li><a href="{% url 'documentation:query' document_name='ckgptune_background' %}">Background</a></li>
    {% endifequal %}

    {% ifequal document_name 'ckgptune_installation' %}
    <li><a class="active" href="{% url 'documentation:query' document_name='ckgptune_installation' %}">Installation</a></li>
    {% else %}
    <li><a href="{% url 'documentation:query' document_name='ckgptune_installation' %}">Installation</a></li>
    {% endifequal %}

    {% ifequal document_name 'ckgptune_examples' %}
    <li><a class="active" href="{% url 'documentation:query' document_name='ckgptune_examples' %}">Examples</a></li>
    {% else %}
    <li><a href="{% url 'documentation:query' document_name='ckgptune_examples' %}">Examples</a></li>
    {% endifequal %}

    </font>
  </ul>

  <div style="margin-left:25%; margin-right:10%; padding:1px 16px; height:90%;">
    <font face="Lucida Grande" size=3px>
      {{ markdown_html | safe }}
    </font>
  </div>
</div>

{% endblock %}