historydb/account/urls.py
from django.urls import path
from django.urls import include

from . import views

app_name = "account"
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('reset-password/', views.reset_password, name='reset-password'),
    path('profile/', views.ProfileDashboard.as_view(), name='profile'),
    path('access-tokens/', views.AccessTokens.as_view(), name='access-tokens'),
    path('add-access-token/', views.AddAccessToken.as_view(), name='add-access-token'),
    path('user-groups/', views.UserGroups.as_view(), name='user-groups'),
    path('add-group/', views.AddGroup.as_view(), name='add-group'),
    path('update-roles/', views.UpdateRoles.as_view(), name='update-roles'),
    path('invite-member/', views.InviteMember.as_view(), name='invite-member'),
    path('data/', views.DataDashboard.as_view(), name='data'),
    path('<str:username>/activate/', views.activate, name='activate'),
]

historydb/historydb/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('documentation/', include('documentation.urls')),
    path('repo/', include('repo.urls')),
    path('account/', include('account.urls')),
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

historydb/main/urls.py
from django.urls import path
from django.urls import include

from . import views

from django.conf.urls import url
from django.contrib import admin

app_name = "main"
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('about', views.about, name='about'),
    path('publications', views.publications, name='publications'),
    url(r'^docs/', include('docs.urls')),
    path('acknowledgement', views.acknowledgement, name='acknowledgement'),
    path('membership', views.membership, name='membership'),
    path('gptune-tutorial-ecp2021', views.gptune_tutorial_ecp2021, name='gptune-tutorial-ecp2021'),
    path('gptune-tutorial-ecp2022', views.gptune_tutorial_ecp2022, name='gptune-tutorial-ecp2022'),
    path('gptune-tutorial-ecp2023', views.gptune_tutorial_ecp2023, name='gptune-tutorial-ecp2023'),
    path('gptune-tutorial-cass2026', views.gptune_tutorial_cass2026, name='gptune-tutorial-cass2026'),
    path('release', views.release, name='release'),
    path('terms-of-use', views.terms_of_use, name='terms-of-use'),
    path('license', views.license, name='license'),
    path('examples', views.Examples.as_view(), name='examples'),
    path('base', views.base, name='base'),
]

historydb/repo/urls.py
from django.urls import path
from django.urls import include

from . import views

app_name = "repo"
urlpatterns = [
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('user-dashboard/', views.UserDashboard.as_view(), name='user-dashboard'),
    path('surrogate-model/', views.SurrogateModel.as_view(), name='surrogate-model'),
    path('model-prediction/', views.ModelPrediction.as_view(), name='model-prediction'),
    path('analysis-dashing-parameter/', views.AnalysisDashingParameter.as_view(), name='analysis-dashing-parameter'),
    path('analysis-dashing-counter/', views.AnalysisDashingCounter.as_view(), name='analysis-dashing-counter'),
    path('sadashboard/', views.SADashboard.as_view(), name='sadashboard'),
    path('sobol-analysis/', views.SobolAnalysis.as_view(), name='sobol-analysis'),
    path('entryaccess/', views.EntryAccess.as_view(), name='entryaccess'),
    path('entrydel/', views.EntryDel.as_view(), name='entrydel'),
    path('upload/', views.Upload.as_view(), name='upload'),
    path('tuning-problems/', views.TuningProblems.as_view(), name='tuning-problems'),
    path('add-tuning-problem-select/', views.AddTuningProblemSelect.as_view(), name='add-tuning-problem-select'),
    path('add-tuning-problem/', views.AddTuningProblem.as_view(), name='add-tuning-problem'),
    path('add-tuning-problem-flexible/', views.AddTuningProblemFlexible.as_view(), name='add-tuning-problem-flexible'),
    path('add-reproducible-workflow/', views.AddReproducibleWorkflow.as_view(), name='add-reproducible-workflow'),
    path('add-tuning-category/', views.AddTuningCategory.as_view(), name='add-tuning-category'),
    path('applications/', views.Applications.as_view(), name='applications'),
    path('add-applications/', views.AddApplications.as_view(), name='add-applications'),
    path('architectures/', views.Architectures.as_view(), name='architectures'),
    path('add-architectures/', views.Architectures.as_view(), name='add-architectures'),
    path('machines/', views.Machines.as_view(), name='machines'),
    path('add-machine/', views.AddMachine.as_view(), name='add-machine'),
    path('analytical-models/', views.AnalyticalModels.as_view(), name='analytical-models'),
    path('add-analytical-model/', views.AddAnalyticalModel.as_view(), name='add-analytical-model'),
    path('export/', views.Export.as_view(), name='export'),
    path('export-all/', views.ExportAll.as_view(), name='export-all'),
    path('direct-download/', views.direct_download, name='direct-download'),
    path('direct-upload/', views.direct_upload, name='direct-upload'),
    path('api-test/', views.api_test, name='api-test'),
    path('archive/<str:perf_data_uid>/', views.query, name='query'),
]

historydb/repo/views.py
from asyncore import write
from ctypes import util
from django.shortcuts import render

# Create your views here.
from django.views import View
from django.http import HttpResponse
from django.http import JsonResponse

from django.views.generic import TemplateView

from datetime import datetime
from django.forms.models import model_to_dict
from django.shortcuts import redirect
from django.urls import reverse_lazy

from django.contrib.auth.models import User
from django.contrib import auth

from dbmanager import HistoryDB_MongoDB

from django.conf import settings

from plotly.offline import plot
import pandas as pd

from dashing.driver import driver

import requests
import os
import json
import ast
import re
import copy
import numpy

class Dashboard(TemplateView):

    def get(self, request, **kwargs):

        historydb = HistoryDB_MongoDB()

        tuning_problems_avail = historydb.load_all_tuning_problems()
        machine_configurations_avail = historydb.get_machine_configurations_avail()
        software_configurations_avail = historydb.get_software_configurations_avail()
        outputs_avail = historydb.get_outputs_avail()
        user_configurations_avail = historydb.get_user_configurations_avail()

        user_email = request.user.email if request.user.is_authenticated else ""

        print ("======== Dashboard GET ========")
        print ("machine_configurations_avail: ", machine_configurations_avail)
        print ("software_configurations_avail: ", software_configurations_avail)
        print ("outputs_avail: ", outputs_avail)
        print ("user_configurations_avail: ", user_configurations_avail)
        print ("user_email: ", user_email)

        context = {
                "tuning_problems_avail" : tuning_problems_avail,
                "machine_configurations_avail" : machine_configurations_avail,
                "software_configurations_avail" : software_configurations_avail,
                "outputs_avail" : outputs_avail,
                "user_configurations_avail" : user_configurations_avail
                }

        return render(request, 'repo/dashboard.html', context)

    def post(self, request, **kwargs):

        historydb = HistoryDB_MongoDB()

        tuning_problems_avail = historydb.load_all_tuning_problems()
        machine_configurations_avail = historydb.get_machine_configurations_avail()
        software_configurations_avail = historydb.get_software_configurations_avail()
        outputs_avail = historydb.get_outputs_avail()
        user_configurations_avail = historydb.get_user_configurations_avail()

        tuning_problem_unique_name = request.POST["tuning_problem"]
        if tuning_problem_unique_name == "":
            context = {
                "header": "Something went wrong",
                "message": "Please choose a tuning problem to search"
            }
            return render(request, 'main/error.html', context)

        tuning_problem_type = historydb.get_tuning_problem_type(tuning_problem_unique_name)
        tuning_problem_info = historydb.get_tuning_problem_info(tuning_problem_unique_name, tuning_problem_type)
        print ("tuning_problem_info: ", tuning_problem_info)

        machine_configurations_list = [ json.loads(val) for val in request.POST.getlist("machine_configurations_list") ]
        software_configurations_list = [ json.loads(val) for val in request.POST.getlist("software_configurations_list") ]
        output_options = request.POST.getlist("output_options")
        user_configurations_list = [ json.loads(val) for val in request.POST.getlist("user_configurations_list") ]
        search_options = request.POST.getlist("search_options")

        user_email = request.user.email if request.user.is_authenticated else ""

        if "func_eval" in search_options:
            func_eval_list = historydb.load_func_eval_filtered(tuning_problem_unique_name = tuning_problem_unique_name,
                    machine_configurations_list = machine_configurations_list,
                    software_configurations_list = software_configurations_list,
                    output_options = output_options,
                    user_configurations_list = user_configurations_list,
                    user_email = user_email,
                    tuning_problem_type = tuning_problem_type)
            num_func_eval = len(func_eval_list)
            for i in range(num_func_eval):
                func_eval_list[i]["id"] = i
        else:
            func_eval_list = []
            num_func_eval = 0

        print ("FUNC_EVAL_LIST: ", func_eval_list)

        if "surrogate_model" in search_options:
            surrogate_model_list = historydb.load_surrogate_models_filtered(tuning_problem_unique_name = tuning_problem_unique_name,
                    machine_configurations_list = machine_configurations_list,
                    software_configurations_list = software_configurations_list,
                    output_options = output_options,
                    user_configurations_list = user_configurations_list,
                    user_email = user_email,
                    tuning_problem_type = tuning_problem_type)
            num_surrogate_models = {}
            for output_option in output_options:
                num_surrogate_models[output_option] = len(surrogate_model_list[output_option])

            for output_option in output_options:
                i = 0
                for surrogate_model in surrogate_model_list[output_option]:
                    surrogate_model["id"] = i
                    i += 1
                    surrogate_model["num_func_eval"] = len(surrogate_model["function_evaluations"])
                    surrogate_model["num_task_parameters"] = len(surrogate_model["task_parameters"])
                    surrogate_model["num_func_eval_per_task"] = \
                            int(len(surrogate_model["function_evaluations"])/len(surrogate_model["task_parameters"]))
        else:
            surrogate_model_list = {}
            for output_option in output_options:
                surrogate_model_list[output_option] = []

            num_surrogate_models = {}
            for output_option in output_options:
                num_surrogate_models[output_option] = 0

        #print ("machine_configurations_avail: ", machine_configurations_avail)
        #print ("software_configurations_avail: ", software_configurations_avail)
        #print ("outputs_avail: ", outputs_avail)
        #print ("user_configurations_avail: ", user_configurations_avail)

        #print ("tuning_problem_unique_name: ", tuning_problem_unique_name)
        #print ("tuning_problem_info: ", tuning_problem_info)
        #print ("machine_configurations_list: ", machine_configurations_list)
        #print ("software_configurations_list: ", software_configurations_list)
        #print ("user_configurations_list: ", user_configurations_list)
        #print ("output_options: ", output_options)
        #print ("search_options: ", search_options)

        #print ("num_surrogate_models: ", num_surrogate_models)

        context = {
                "tuning_problem_unique_name" : tuning_problem_unique_name,
                "tuning_problem_info" : tuning_problem_info,
                "tuning_problems_avail" : tuning_problems_avail,
                "machine_configurations_avail" : machine_configurations_avail,
                "software_configurations_avail" : software_configurations_avail,
                "outputs_avail" : outputs_avail,
                "user_configurations_avail" : user_configurations_avail,
                "func_eval_list" : func_eval_list,
                "num_func_eval" : num_func_eval,
                "surrogate_model_list" : surrogate_model_list,
                "num_surrogate_models" : num_surrogate_models,
                "machine_configurations_list" : json.dumps(machine_configurations_list),
                "software_configurations_list" : json.dumps(software_configurations_list),
                "output_options" : json.dumps(output_options),
                "user_configurations_list" : json.dumps(user_configurations_list),
                "search_options" : json.dumps(search_options)
                }

        return render(request, 'repo/dashboard.html', context)

class UserDashboard(TemplateView):

    def get(self, request, **kwargs):
        print ("======== User Dashboard GET ========")

        historydb = HistoryDB_MongoDB()

        user_email = request.user.email

        func_eval_list = historydb.load_func_eval_by_user(user_email = user_email)
        num_func_eval = len(func_eval_list)
        print ("num_func_eval: ", num_func_eval)
        num_evals_per_page = 30
        if (num_func_eval%num_evals_per_page) == 0:
            num_pages_func_eval = int(num_func_eval/num_evals_per_page)
        else:
            num_pages_func_eval = int(num_func_eval/num_evals_per_page)+1
        if (num_pages_func_eval == 0):
            num_pages_func_eval = 1
        current_page_func_eval = int(request.GET.get("current_page_func_eval", 0))
        print ("current_page_func_eval: ", current_page_func_eval)
        start_index = (current_page_func_eval)*num_evals_per_page
        end_index = (current_page_func_eval+1)*num_evals_per_page
        if end_index > num_func_eval:
            end_index = num_func_eval
        func_eval_web = func_eval_list[start_index:end_index]
        for i in range(len(func_eval_web)):
            func_eval_web[i]["id"] = start_index+i
        print (func_eval_web)

        surrogate_models = historydb.load_surrogate_models_by_user(user_email = user_email)
        num_surrogate_models = len(surrogate_models)
        num_surrogate_model_per_page = 30
        if (num_surrogate_models %num_surrogate_model_per_page) == 0:
            num_pages_surrogate_models = num_surrogate_models/num_surrogate_model_per_page
        else:
            num_pages_surrogate_models = int(num_surrogate_models/num_surrogate_model_per_page)+1

historydb/repo/templates/repo/addapp.html
<!-- Author: Younghyun Cho <younghyun@berkeley.edu> -->

<!doctype html>

{% extends 'main/base.html' %}
{% load static %}
{% block content %}

<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>

<link href="{% static 'css/form-validation.css' %}" rel="stylesheet">

<script>
  $(document).ready(function () {
    $('#nav-item-repo').addClass('active');
  });

  function UpdateUploadOptionFile() {
    document.getElementById('file_upload_form_div').style.display = 'block';
    document.getElementById('text_upload_form_div').style.display = 'none';
  }

  function UpdateUploadOptionText() {
    document.getElementById('file_upload_form_div').style.display = 'none';
    document.getElementById('text_upload_form_div').style.display = 'block';
  }

  function AddToggle() {
    if (document.getElementById('add-toggle').checked) {
      document.getElementById('add-form').style.display = 'block';
    } else {
      document.getElementById('add-form').style.display = 'none';
    }
  }
</script>

<div class="container" style="max-width: 560px">
  <div class="py-5 text-center">
    <h1>Add Application</h1>
  </div>

  <div class="container">
    <form method="POST" action="{% url 'repo:addapp' %}" enctype="multipart/form-data" class="needs-validation" novalidate>
      {% csrf_token %}
      <div class="mb-3">
        <label for="applicationVal">Please check if we already have the same application</label>
        <select class="custom-select d-block w-100" name="application" id="applicationVal">
          <option value="" label="Search..." selected></option>
          {% if applications_avail %}
          {% for application_avail in applications_avail %}
          <option value="{{ application_avail.name }}">{{ application_avail.name }} ({{ application_avail.library }})</option>
          {% endfor %}
          {% else %}
          {% endif %}
        </select>
      </div>

      <div class="mb-3">
        <label for="add-toggle">If not exists?</label>
        <input id="add-toggle" type="checkbox" data-toggle="toggle" onchange="AddToggle()" data-on="Now Adding a New Application" data-width="100%" data-height="20" data-off="Click to Add Application" data-onstyle="primary" data-offstyle="success">
      </div>

      <div id="add-form" style="display:none;">

        <div class="mb-3">
          <label for="application_name">Name of your application</label>
          <input type="text" class="form-control" id="application_name" name="application_name">
        </div>

        <div class="mb-3">
          <label for="application_category">Category or library of the application</label>
          <input type="text" class="form-control" id="application_category" name="application_category">
        </div>

        <div class="mb-3">
          <label for="application_description">Please describe little bit about your application</label>
          <textarea class="form-control" id="application_description" name="application_description" rows="5"></textarea>
        </div>

        <div class="mb-3">
          <hr class="mb-4">
          <button class="btn btn-primary btn-lg btn-block" type="submit">Submit</button>
        </div>

      </div>
    </form>
  </div>
</div>

{% endblock %}

historydb/repo/templates/repo/user-groups.html
<!-- Author: Younghyun Cho <younghyun@berkeley.edu> -->

<!doctype html>

{% extends 'main/base.html' %}
{% load static %}
{% block content %}

<link href="{% static 'css/form-validation.css' %}" rel="stylesheet">

<script>
  $(document).ready(function () {
    $('#nav-item-account').addClass('active');
  });
</script>

<div class="container">
  <div class="py-5 text-center">
    <h1>My Collaboration Groups</h1>
  </div>

  <div class="d-block text-right mt-3">
    <a id="add_app_tab" href="{% url 'repo:add-group' %}">Add a collboration group</a>
  </div>

  <div class="table-responsive">
    <br>
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>#</th>
          <th>Group Name</th>
          <th>My Role</th>
          <th>Members</th>
          <th>Edit</th>
          <th>Invite</th>
        </tr>
      </thead>
      <tbody>
        {% for group_data in user_groups %}
          <tr>
            <td>{{ group_data.no }}</td>
            <td>{{ group_data.group_name }}</td>
            <td>{{ group_data.my_role }}</td>
            <td>
              <a data-toggle="modal" data-target="#membersModalLong_{{ group_data.uid }}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-text" viewBox="0 0 16 16">
                  <path d="M5 4a.5.5 0 0 0 0 1h6a.5.5 0 0 0 0-1H5zm-.5 2.5A.5.5 0 0 1 5 6h6a.5.5 0 0 1 0 1H5a.5.5 0 0 1-.5-.5zM5 8a.5.5 0 0 0 0 1h6a.5.5 0 0 0 0-1H5zm0 2a.5.5 0 0 0 0 1h3a.5.5 0 0 0 0-1H5z"/>
                  <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm10-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z"/>
                </svg>
              </a>
            </td>
            <td>
              {% ifequal group_data.my_role "owner" %}
              <a data-toggle="modal" data-target="#editModalLong_{{ group_data.uid }}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                  <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                  <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                </svg>
              </a>
              {% else %}
              <p style="color:gray;">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
              </svg>
              </p>
              {% endifequal %}
            </td>
            <td>
              {% ifequal group_data.my_role "owner" %}
              <p style="color:black">
              <a data-toggle="modal" data-target="#inviteModalLong_{{ group_data.uid }}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16">
                  <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                  <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
                </svg>
              </a>
              </p>
              {% else %}
              <p style="color:gray;">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16">
                <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
              </svg>
              </p>
              {% endifequal %}
            </td>

            <div class="modal fade" id="membersModalLong_{{ group_data.uid }}" tabindex="-1" role="dialog" aria-labelledby="membersModalLongTitle" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="membersModalLongTitle">Group Members</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    {% for member in group_data.members %}
                    <div class="row mb-3">
                      <div class="col">
                        <label>Email</label>
                        <input type="email" class="form-control" name="invites_email" value={{ member.email }} readonly>
                      </div>
                      <div class="col">
                        <label>Role</label>
                        <select class="custom-select d-block w-100" name="invites_roles" style="pointer-events: none; background-color:rgba(0,0,0,0.08);">
                          {% ifequal member.role "owner" %}
                            <option value="owner" label="Owner" selected></option>
                            <option value="member" label="Member"></option>
                          {% else %}
                            <option value="owner" label="Owner"></option>
                            <option value="member" label="Member" selected></option>
                          {% endifequal %}
                        </select>
                      </div>
                    </div>
                    {% endfor %}
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Okay</button>
                  </div>
                </div>
              </div>
            </div>

            <div class="modal fade" id="detailModalLong_{{ group_data.uid }}" tabindex="-1" role="dialog" aria-labelledby="detailModalLongTitle" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="detailModalLongTitle">Details of the Function Evaluation Data</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <form method="POST" action="{% url 'repo:entrydel' %}">
                    {% csrf_token %}
                    <input type="hidden" name="entry_uid" value={{ group_data.uid }}></input>
                    <input type="hidden" name="application_name" value={{ group_data.application }}></input>
                    <div class="modal-body">
                      <pre>{{ group_data | pprint }}</pre>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>

            <div class="modal fade" id="editModalLong_{{ group_data.uid }}" tabindex="-1" role="dialog" aria-labelledby="editModalLongTitle" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="editModalLongTitle">Change Role</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <form method="POST" action="{% url 'repo:update-roles' %}">
                    {% csrf_token %}
                    <input type="hidden" name="group_uid" value={{ group_data.uid }}></input>

                    <div class="modal-body">
                      {% for member in group_data.members %}
                      <div class="row mb-3">
                        <div class="col">
                          <label>Email</label>
                          <input type="email" class="form-control" name="invites_emails" value={{ member.email }} readonly>
                        </div>
                        <div class="col">
                          <label>Role</label>
                          {% ifequal member.role "owner" %}
                          <select class="custom-select d-block w-100" name="invites_roles" style="pointer-events: none; background-color:rgba(0,0,0,0.08);">
                            <option value="owner" label="Owner" selected></option>
                            <option value="member" label="Member"></option>
                          </select>
                          {% else %}
                          <select class="custom-select d-block w-100" name="invites_roles">
                            <option value="owner" label="Owner"></option>
                            <option value="member" label="Member" selected></option>
                          </select>
                          {% endifequal %}
                        </div>
                      </div>
                      {% endfor %}
                    </div>

                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                      <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>

            <div class="modal fade" id="inviteModalLong_{{ group_data.uid }}" tabindex="-1" role="dialog" aria-labelledby="inviteModalLongTitle" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="inviteModalLongTitle">Invite Member</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <form method="POST" action="{% url 'repo:invite-member' %}">
                    {% csrf_token %}
                    <input type="hidden" name="group_uid" value={{ group_data.uid }}></input>

                    <div class="modal-body">
                      <div class="row mb-3">
                        <div class="col">
                          <label>Email</label>
                          <input type="email" class="form-control" name="invite_email">
                        </div>
                        <div class="col">
                          <label>Role</label>
                          <select class="custom-select d-block w-100" name="invite_role">
                            <option value="owner" label="Owner"></option>
                            <option value="member" label="Member" selected></option>
                          </select>
                        </div>
                      </div>
                    </div>

                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                      <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>

        {% endfor %}
      </tbody>
    </table>
    <table>
    </table>
  </div>
</div>

{% endblock %}